name: Node.js App Deploy to AKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: CKA
        resource-group: Avadhoot

    - name: Build and Push Docker image to ACR
      env:
        ACR_NAME: avadhoot.azurecr.io # e.g., myregistry.azurecr.io
        IMAGE_NAME: Avadhoot
        IMAGE_TAG: latest
      run: |
        az acr login --name $ACR_NAME
        docker build -t $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG .
        docker push $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
